service: sls18-demo-basic
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DEBUG: 0

functions:
  check:
    memorySize: 1536
    timeout: 180
    handler: index.handler
    events:
      - schedule: rate(10 minutes)

plugins:
  - serverless-hooks-plugin

package:
  artifact: ./package.zip

custom:
  hooks:
    package:initialize:
      - npm run package
